### ISSUE TITLE
[BUG][Ruby] Avoid mentioning issues from version not used anymore

### ISSUE THREAD

**Issue by GauthierPLM** [rakshazi/yourlanguagesucks.com#3]
[Most developers in the market](https://www.jetbrains.com/lp/devecosystem-2019/ruby/) now use a flavor of Ruby 2, with a majority using one of the 3 or 4 latest versions.

However, on the Ruby Sucks page, some elements refers to old version or versions not supported for a long time now. Notably:

> - Unicode support should have been built in from 1.0, not added after much complaining in 1.9/2.0 in 2007
> - No support for negative / positive look-behind in regular expressions in 1.8
> - There are no smart and carefully planned changes that can’t break compatibility; even minor releases can break compatibility: See “Compatibility issues” and “fileutils”. This leads to multiple recommended stable versions: both 1.8.7 and 1.9.1 for Windows. Which one to use?

Some project (in particular in big companies) still use old version of Ruby, but they are usually in maintenance only. Projects that are actively developed are usually migrated to more recent versions. Additionally, Ruby programs running on version older than Ruby 2.2 are not common anymore.

So in order to remain relevant, only issues that have an impact on version currently used by a high number of developers should be mentioned. Someone reading yourlanguagesucks.com might look for a new language to learn or adopt. No need to mention him about old things that got acknowledged, fixed, and disappeared for a long time now.

**Comment by rakshazi** [comment]
Hi GauthierPLM,
thank you for review, I'll add changes today!

**Comment by rakshazi** [comment]
Done
